/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdsaparking2;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class dashboardGUI extends javax.swing.JFrame {

    ImageIcon imageCloseh = scaleImage("resources/closeh.png", 24);
    ImageIcon imageClose = scaleImage("resources/close.png", 24);
    // global variable to move the undecorated jframe
    int xMouse;
    int yMouse;
    
    public dashboardGUI() {
        initComponents();
        //set the application icon
        setIconImage(Toolkit.getDefaultToolkit().getImage("resources/logo.png"));
        //makes the frame have rounded borders
         Shape roundedRectangle = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20);

        // set the shape of the frame
        setShape(roundedRectangle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        lblRemaining = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtVehicleNumber = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        txtParked = new javax.swing.JTextField();
        txtParkSpot = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblParkTime = new javax.swing.JLabel();
        lblParkSpot = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblRemainingNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setUndecorated(true);
        setResizable(false);

        pnlNavigation.setBackground(new java.awt.Color(38, 38, 67));
        pnlNavigation.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        pnlNavigation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlNavigationMouseDragged(evt);
            }
        });
        pnlNavigation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNavigationMousePressed(evt);
            }
        });

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(244, 250, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(244, 250, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo.png"))); // NOI18N
        jLabel8.setText("Parking Zone");
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(251, 251, 251)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlNavigationLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );

        btnClose.setIcon(imageClose);

        pnlBody.setBackground(new java.awt.Color(58, 58, 77));
        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRemaining.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRemaining.setForeground(new java.awt.Color(255, 255, 255));
        lblRemaining.setText("Remaining Slots");
        pnlBody.add(lblRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 150, -1));

        txtName.setBackground(new java.awt.Color(58, 58, 77));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNameMouseExited(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlBody.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 200, -1));

        txtVehicleNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtVehicleNumber.setBackground(new java.awt.Color(58, 58, 77));
        txtVehicleNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVehicleNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtVehicleNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleNumberFocusLost(evt);
            }
        });
        pnlBody.add(txtVehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, -1));

        txtLicense.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtLicense.setBackground(new java.awt.Color(58, 58, 77));
        txtLicense.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLicense.setForeground(new java.awt.Color(255, 255, 255));
        txtLicense.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicenseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLicenseFocusLost(evt);
            }
        });
        pnlBody.add(txtLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));

        txtParked.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtParked.setBackground(new java.awt.Color(58, 58, 77));
        txtParked.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtParked.setForeground(new java.awt.Color(255, 255, 255));
        txtParked.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtParkedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtParkedFocusLost(evt);
            }
        });
        pnlBody.add(txtParked, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 200, -1));

        txtParkSpot.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtParkSpot.setBackground(new java.awt.Color(58, 58, 77));
        txtParkSpot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtParkSpot.setForeground(new java.awt.Color(255, 255, 255));
        txtParkSpot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtParkSpotFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtParkSpotFocusLost(evt);
            }
        });
        pnlBody.add(txtParkSpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, -1));

        btnAdd.setBackground(new java.awt.Color(94, 237, 181));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Ticket");
        btnAdd.setActionCommand("");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlBody.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, -1));

        btnDelete.setBackground(new java.awt.Color(94, 237, 181));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Last");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlBody.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 200, -1));

        btnView.setBackground(new java.awt.Color(94, 237, 181));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Last Ticket");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        pnlBody.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("15/50");
        pnlBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 87, -1));

        lblName.setBackground(new java.awt.Color(244, 250, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(244, 250, 255));
        lblName.setText("Name");
        pnlBody.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, -1));

        lblParkTime.setBackground(new java.awt.Color(244, 250, 255));
        lblParkTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblParkTime.setForeground(new java.awt.Color(244, 250, 255));
        lblParkTime.setText("Parked Time");
        pnlBody.add(lblParkTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 100, -1));

        lblParkSpot.setBackground(new java.awt.Color(244, 250, 255));
        lblParkSpot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblParkSpot.setForeground(new java.awt.Color(244, 250, 255));
        lblParkSpot.setText("Park Spot");
        pnlBody.add(lblParkSpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, -1));

        lblLicense.setBackground(new java.awt.Color(244, 250, 255));
        lblLicense.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLicense.setForeground(new java.awt.Color(244, 250, 255));
        lblLicense.setText("Licence No.");
        pnlBody.add(lblLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, -1));

        lblRemainingNumber.setBackground(new java.awt.Color(244, 250, 255));
        lblRemainingNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRemainingNumber.setForeground(new java.awt.Color(244, 250, 255));
        lblRemainingNumber.setText("Vehicle No.");
        pnlBody.add(lblRemainingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        viewPreviousGUI pn = new viewPreviousGUI();
        pn.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setIcon(imageCloseh);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setIcon(imageClose);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMousePressed

    private void pnlNavigationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNavigationMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlNavigationMousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseDragged

    private void pnlNavigationMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNavigationMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x- xMouse,y-yMouse);
    }//GEN-LAST:event_pnlNavigationMouseDragged

    private void txtNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseEntered

    private void txtNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseExited

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        fieldHover(txtName);
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        fieldLeave(txtName);
    }//GEN-LAST:event_txtNameFocusLost

    private void txtVehicleNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleNumberFocusGained
        // TODO add your handling code here:
        fieldHover(txtVehicleNumber);
    }//GEN-LAST:event_txtVehicleNumberFocusGained

    private void txtVehicleNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleNumberFocusLost
        // TODO add your handling code here:
        fieldLeave(txtVehicleNumber);
    }//GEN-LAST:event_txtVehicleNumberFocusLost

    private void txtParkedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkedFocusGained
        // TODO add your handling code here:
        fieldHover(txtParked);
    }//GEN-LAST:event_txtParkedFocusGained

    private void txtLicenseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusGained
        // TODO add your handling code here:
        fieldHover(txtLicense);
    }//GEN-LAST:event_txtLicenseFocusGained

    private void txtParkSpotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkSpotFocusGained
        // TODO add your handling code here:
        fieldHover(txtParkSpot);
    }//GEN-LAST:event_txtParkSpotFocusGained

    private void txtParkSpotFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkSpotFocusLost
        // TODO add your handling code here:
        fieldLeave(txtParkSpot);
    }//GEN-LAST:event_txtParkSpotFocusLost

    private void txtLicenseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicenseFocusLost
        // TODO add your handling code here:
        fieldLeave(txtLicense);
    }//GEN-LAST:event_txtLicenseFocusLost

    private void txtParkedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkedFocusLost
        // TODO add your handling code here:
        fieldLeave(txtParked);
    }//GEN-LAST:event_txtParkedFocusLost

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardGUI().setVisible(true);
            }
        });
    }
    
    public ImageIcon scaleImage(String location, int size) {
    BufferedImage img = null;
    try {
        img = ImageIO.read(new File(location));
        int width = img.getWidth();
        int height = img.getHeight();
        int newWidth = size;
        int newHeight = size;
        if (width > height) {
            newHeight = (int) (((double) size / width) * height);
        } else {
            newWidth = (int) (((double) size / height) * width);
        }
        Image dimg = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        return new ImageIcon(dimg);
    } catch (IOException e) {
        e.printStackTrace();
        return null;
    }
}
    public void fieldHover(JTextField fieldName){
        fieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(94, 237, 181)));
    }
    public void fieldLeave(JTextField fieldName){
        fieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblParkSpot;
    private javax.swing.JLabel lblParkTime;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblRemainingNumber;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtParkSpot;
    private javax.swing.JTextField txtParked;
    private javax.swing.JTextField txtVehicleNumber;
    // End of variables declaration//GEN-END:variables
}
